# 配置4个EurekaClient, 分4个zone,分属region-east、region-west
server:
  port: 8071
spring:
  application:
    name: ${project.name}
eureka:
  client:
    prefer-same-zone-eureka: true
    region: region-east
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-east: zone1,zone2
  instance:
    metadataMap.zone: zone1