spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    zuul-gray-client-demo:
      path: /client/**
      serviceId: zuul-gray-client-demo
  ribbon:
    eager-load:
      enabled: true # Zuul内部默认使用Ribbon来调用远程服务，所以由于ribbon的原因，在我们部署好所有组件
                    # 之后，第一次经过zuul的调用往往会去注册中心读取服务列表，初始化ribbon负载信息。
                    # 这是一种懒加载策略，但是这个过程是极其耗时的，尤其是服务过多的时候。
                    # 为了避免这个问题，在启动zuul的时候加先饥饿加载其信息。