# 使用2个zuul来演示fallback到remote region
# 一个属于 region-east
# 一个属于 region-west

server:
  port: 10003
eureka:
  instance:
    metadataMap.zone: zone3
  client:
    register-with-eureka: true
    fetch-registry: true
    region: region-west
    service-url:
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    availability-zones:
      region-west: zone3,zone4